-- Generated by pnpm generate:sql. Do not edit.
CREATE TABLE IF NOT EXISTS "accounts" (
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "account_status" TEXT NOT NULL DEFAULT 'active',
    "tokens" TEXT NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,

    PRIMARY KEY ("email", "app_id")
);
CREATE TABLE IF NOT EXISTS "thread_lists" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "folder" TEXT NOT NULL DEFAULT '',
    "query" TEXT NOT NULL DEFAULT '',
    "label_ids" TEXT NOT NULL DEFAULT '',
    "page_token" TEXT NOT NULL DEFAULT '',
    "max_results" INTEGER NOT NULL DEFAULT 0,
    "data" TEXT NOT NULL,
    "ttl_ms" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "thread_lists_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "threads" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "thread_id" TEXT NOT NULL,
    "data" TEXT NOT NULL,
    "ttl_ms" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "threads_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "labels" (
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "data" TEXT NOT NULL,
    "ttl_ms" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("email", "app_id"),
    CONSTRAINT "labels_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "label_counts" (
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "data" TEXT NOT NULL,
    "ttl_ms" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("email", "app_id"),
    CONSTRAINT "label_counts_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "profiles" (
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "data" TEXT NOT NULL,
    "ttl_ms" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("email", "app_id"),
    CONSTRAINT "profiles_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "calendar_lists" (
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "data" TEXT NOT NULL,
    "ttl_ms" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY ("email", "app_id"),
    CONSTRAINT "calendar_lists_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "calendar_events" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "calendar_id" TEXT NOT NULL DEFAULT '',
    "time_min" TEXT NOT NULL DEFAULT '',
    "time_max" TEXT NOT NULL DEFAULT '',
    "query" TEXT NOT NULL DEFAULT '',
    "max_results" INTEGER NOT NULL DEFAULT 0,
    "page_token" TEXT NOT NULL DEFAULT '',
    "data" TEXT NOT NULL,
    "ttl_ms" INTEGER NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "calendar_events_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "sync_states" (
    "email" TEXT NOT NULL,
    "app_id" TEXT NOT NULL DEFAULT '406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com',
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,

    PRIMARY KEY ("email", "app_id", "key"),
    CONSTRAINT "sync_states_email_app_id_fkey" FOREIGN KEY ("email", "app_id") REFERENCES "accounts" ("email", "app_id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "thread_lists_email_app_id_folder_query_label_ids_page_token_max_results_key" ON "thread_lists"("email", "app_id", "folder", "query", "label_ids", "page_token", "max_results");
CREATE UNIQUE INDEX "threads_email_app_id_thread_id_key" ON "threads"("email", "app_id", "thread_id");
CREATE UNIQUE INDEX "calendar_events_email_app_id_calendar_id_time_min_time_max_query_max_results_page_token_key" ON "calendar_events"("email", "app_id", "calendar_id", "time_min", "time_max", "query", "max_results", "page_token");
